---
- include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "{{ ansible_os_family }}.yml"
  when: not skip_engine

# Install docker-py
- import_tasks: docker_py.yml
  when: not skip_docker_py

# Adds the Docker admin users to the Docker group
- import_tasks: docker_group.yml
  when: not skip_group

# Setup the Docker Swarm Cluster
- import_tasks: swarm_cluster.yml
  when: not skip_swarm
